use crate::mosaic::configuration::Configuration;

mod monitors;

pub fn render_configuration(configuration: &Configuration) -> String {
    let mut output = format!(
        r#"-- This file is managed by MOSAIC.
-- Do not edit this file manually.
--
-- MOSAIC version: {}
-- Generated automatically.
--

"#,
        env!("CARGO_PKG_VERSION")
    );

    for monitor in &configuration.monitors {
        output.push_str(&monitors::render_monitor(monitor));
        output.push('\n');
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mosaic::configuration::monitors::{
        Monitor, MonitorMode, MonitorPosition, MonitorScale, Rotation,
    };

    #[test]
    fn renders_empty_configuration() {
        let configuration = Configuration::new();

        assert_eq!(
            render_configuration(&configuration),
            concat!(
                "-- This file is managed by MOSAIC.\n",
                "-- Do not edit this file manually.\n",
                "--\n",
                "-- MOSAIC version: ",
                env!("CARGO_PKG_VERSION"),
                "\n",
                "-- Generated automatically.\n",
                "--\n",
                "\n",
            )
        );
    }

    #[test]
    fn renders_monitors_from_configuration() {
        let configuration = Configuration {
            monitors: vec![
                Monitor {
                    output: "DP-3".into(),
                    disabled: false,
                    mode: MonitorMode::Custom("2560x1440@144".into()),
                    scale: MonitorScale::Fixed(1.0),
                    position: MonitorPosition::Fixed { x: 0, y: 0 },
                    rotation: Rotation::Degrees0,
                    flip: false,
                    mirror: None,
                },
                Monitor {
                    output: "DP-1".into(),
                    disabled: false,
                    mode: MonitorMode::Custom("2560x1440@144".into()),
                    scale: MonitorScale::Fixed(1.0),
                    position: MonitorPosition::Fixed { x: 2560, y: 0 },
                    rotation: Rotation::Degrees0,
                    flip: false,
                    mirror: None,
                },
            ],
        };

        let result = render_configuration(&configuration);

        assert_eq!(
            result,
            concat!(
                "-- This file is managed by MOSAIC.\n",
                "-- Do not edit this file manually.\n",
                "--\n",
                "-- MOSAIC version: ",
                env!("CARGO_PKG_VERSION"),
                "\n",
                "-- Generated automatically.\n",
                "--\n",
                "\n",
                "hl.monitor({ output = \"DP-3\", mode = \"2560x1440@144\", scale = 1, position = \"0x0\" })\n",
                "hl.monitor({ output = \"DP-1\", mode = \"2560x1440@144\", scale = 1, position = \"2560x0\" })\n",
            )
        );
    }
}
