use mosaic::{
    Configuration, Monitor, MonitorMode, MonitorPosition, MonitorScale, Rotation,
    render_hyprland_configuration,
};

#[test]
fn renders_three_monitor_configuration() {
    let configuration = Configuration {
        monitors: vec![
            Monitor {
                output: "DP-3".into(),
                disabled: false,
                mode: MonitorMode::Custom("2560x1440@144".into()),
                scale: MonitorScale::Fixed(1.0),
                position: MonitorPosition::Fixed { x: 0, y: 0 },
                rotation: Rotation::Degrees0,
                flip: false,
                mirror: None,
            },
            Monitor {
                output: "DP-1".into(),
                disabled: false,
                mode: MonitorMode::Custom("2560x1440@144".into()),
                scale: MonitorScale::Fixed(1.0),
                position: MonitorPosition::Fixed { x: 2560, y: 0 },
                rotation: Rotation::Degrees0,
                flip: false,
                mirror: None,
            },
            Monitor {
                output: "DP-2".into(),
                disabled: false,
                mode: MonitorMode::Custom("2560x1440@144".into()),
                scale: MonitorScale::Fixed(1.0),
                position: MonitorPosition::Fixed { x: 5120, y: 0 },
                rotation: Rotation::Degrees270,
                flip: false,
                mirror: None,
            },
        ],
    };

    let result = render_hyprland_configuration(&configuration);

    let expected = concat!(
        "-- This file is managed by MOSAIC.\n",
        "-- Do not edit this file manually.\n",
        "--\n",
        "-- MOSAIC version: ",
        env!("CARGO_PKG_VERSION"),
        "\n",
        "-- Generated automatically.\n",
        "--\n",
        "\n",
        "hl.monitor({ output = \"DP-3\", mode = \"2560x1440@144\", scale = 1, position = \"0x0\" })\n",
        "hl.monitor({ output = \"DP-1\", mode = \"2560x1440@144\", scale = 1, position = \"2560x0\" })\n",
        "hl.monitor({ output = \"DP-2\", mode = \"2560x1440@144\", scale = 1, position = \"5120x0\", transform = 3 })\n",
    );

    assert_eq!(result, expected);
}
